#%RAML 1.0 Library
# Developed by: Himanshu Bansal
# Date: 26 November'17
# customer.raml


types:
  Customer:
    #                                   #
    # add attributes of Customer below  #
    #                                   #
    cust_id:
      type: number[]
      desription: |
        unique id of the customer
    first-name:
      type: string[]
      description: |
        First-name of the customer
    last-name:
      type: string[]
      description: |
        Last-name of the customer
    address:
      type: string[]
      description: |
        stores customer address
