#%RAML 1.0 Library
types:
  Customer:
    cust_id:
      type: integer[]
      desription: |
        unique id of the customer
    first-name:
      type: string[]
      description: |
        First-name of the customer

    last-name:
      type: string[]
      description: |
        Last-name of the customer

    address:
      type: string[]
      description: |
        stores customer address
