#%RAML 1.0 Library
types:
  Order:
    order_id:
      type: integer[]
      desription: |
        unique identifier for order

    # order_date
    # cust_id
    # prod_id
    # price
    # no_of_items
    # order_received_date
