#%RAML 1.0 Library
# Developed by: Himanshu Bansal
# Date: 26 November'17
# order.raml

types:
  Order:
    #                                   #
    # add attributes of Order below     #
    #                                   #

    order_id:
      type: number[]
      desription: |
        unique identifier for order
      required: true
    order_date:
      type: datetime[]
      description: |
        timestamp of order
    total_cost:
      type: float[]
      description: |
        total cost of the order
