#%RAML 1.0 Library
# Developed by: Himanshu Bansal
# Date: 26 November'17
# orderdetails.raml

types:
  OrderDetails:
    uses:
      Customer: customer.raml
      Product: product.raml
      Order: order.raml

      #                                        #
      # add attributes of OrderDetails below   #
      #                                        #

      order_detail_id:
        type: number[]
        description: |
          unique key identifier for order record
      cust_id:
        type: number[]
        description: |
          foreign key identifier for customer record
        required: true
      prod_id:
        type: number[]
        description: |
          foreign key identifier for product
        required: true
      order_id:
        type: number[]
        description: |
          foreign key identifier for order
