#%RAML 1.0 Library
types:
  Product:
    prod_id:
      type: number[]
      desription: |
        unique id of the product
    prod_name:
      type: string[]
      description: |
        name of the product
    prod_description:
      type: string[]
      description: |
        descripton of the product
    prod_cost:
      type: float[]
      description: |
        cost of the product
    prod_status:
      type: string[]
      description: |
        status of the product (available/out of stock)
