#%RAML 1.0 Library
types:
  Product:
    prod_id:
      type: integer[]
      desription: |
        unique id of the product

    #product_name
    #product_description
    #product_specifications
    #product_color
