#%RAML 1.0 Library
# Developed by: Himanshu Bansal
# Date: 26 November'17
# product.raml

types:
  Product:
    #                                   #
    # add attributes of Product below  #
    #                                   #
    
    prod_id:
      type: number[]
      desription: |
        unique id of the product
    prod_name:
      type: string[]
      description: |
        name of the product
    prod_description:
      type: string[]
      description: |
        descripton of the product
    prod_cost:
      type: float[]
      description: |
        cost of the product
    prod_status:
      type: string[]
      description: |
        status of the product (available/out of stock)
